### ISSUE TITLE
Why did the experiment seem to stop after 1800 rounds? 

### ISSUE THREAD

**Issue by fengshaw1** [ybdai7/Chameleon-durable-backdoor#12]
Before 1800 rounds, the epoch number will continue to be displayed, but after 1800 rounds, this number is no longer displayed. Why is this?
![image](https://github.com/user-attachments/assets/84bb284f-1164-4490-ae63-e5830f5ecb0c)

**Comment by ybdai7** [comment]
Hi,

Is the program halted in unexpected scenarios? and if so, could you provide me with the error information for reference? Basically, the poisoning starts after 1800 global rounds, the epoch number you mentioned will continuous be recorded in the log file after the poisoning training finishes. Please carefully check your yaml file, and maybe the modification you made to codes.

**Comment by fengshaw1** [comment]
I see the yaml file run 10000 epochs, but this program run after 1800 rounds, it seems run very slow.Is this right? or some other reasons.
![image](https://github.com/user-attachments/assets/658cf3ad-443a-4886-bc3b-aed7b27400cc)
![image](https://github.com/user-attachments/assets/828e981e-58b0-412e-8c72-97c060b762c3)

**Comment by ybdai7** [comment]
Based on your screenshots, the program should be still running. Poisoning stage is surely slower that normal training, as it involves contrastive learning conducted by adversaries. Please do check your computation resources, and whether pytorch is working on GPU.

**Comment by fengshaw1** [comment]
ok, i have tried twice more, and the poisoning stage my NVIDIA-4070S Graphics fan not work.Wait me do more experiment and comment.
