### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by 1imy** [ybdai7/Chameleon-durable-backdoor#3]
def load_edge_case(self):
        with open('./data/edge-case/southwest_images_new_train.pkl', 'rb') as train_f:
            saved_southwest_dataset_train = pickle.load(train_f)
        with open('./data/edge-case/southwest_images_new_test.pkl', 'rb') as test_f:
            saved_southwest_dataset_test = pickle.load(test_f)
and run it will raise a problem
FileNotFoundError: [Errno 2] No such file or directory: './data/edge-case/southwest_images_new_train.pkl'
how to solve it?

**Comment by ybdai7** [comment]
Hi, 

For the edge-case datasets, you can acquire them following the instructions of https://github.com/ksreenivasan/OOD_Federated_Learning, which is the official repo of the Yes-you-can-really-backdoor-FL paper.

Thanks

**Comment by 1imy** [comment]
thank you so much!
