### ISSUE TITLE
ask for a question

### ISSUE THREAD

**Issue by 1imy** [ybdai7/Chameleon-durable-backdoor#4]
I noticed during the process of change that the tensor named mask_cross_feature in loss.py has not changed. May I ask what is the purpose of these few lines of weight code? Thank you for your answer!

                if ind < poison_per_batch*poison_images_len:
                    label_1_row_eq = torch.eq(label_flatten, 1).float().to(device) * down_scale_weight 
                    label_1_row_nq = torch.ne(label_flatten, 1).float().to(device)
                    label_1_row = label_1_row_eq + label_1_row_nq
                    mask_cross_feature[ind,:] = mask_cross_feature[ind,:] * label_1_row
                if label == 1:
                    mask_cross_feature[ind, 0:poison_per_batch*poison_images_len] = mask_cross_feature[ind, 0:poison_per_batch*poison_images_len] * down_scale_weight

**Comment by ybdai7** [comment]
Hi,

These codes are redundant. Removing them would not make a difference to the final result.

Thanks.
