### ISSUE TITLE
one ask

### ISSUE THREAD

**Issue by fengshaw1** [ybdai7/Chameleon-durable-backdoor#7]
Hello author! Your work is outstanding! How to read your code? I understand that your code is based on the paper "how to backdoor". How did you read his code in the first place? Please give me some advice, thank you!

**Comment by ybdai7** [comment]
Hi,

I suggest you could work on understanding my recent repo (https://github.com/ybdai7/Backdoor-indicator-defense), which is a better organized one and more beginner-friendly i think.

**Comment by fengshaw1** [comment]
OK、thanks a lot.Nice work！！！
