### ISSUE TITLE
Question about the implementation of Differential Privacy

### ISSUE THREAD

**Issue by simonla82** [ybdai7/Chameleon-durable-backdoor#9]
While working with your code, a few questions regarding differential privacy in it occurred to me:

1. Why do you apply the differential privacy clipping at three different places during the malicious training ([L255-L271](https://github.com/ybdai7/Chameleon-durable-backdoor/blob/main/training.py#L255-L271), [L507-L523](https://github.com/ybdai7/Chameleon-durable-backdoor/blob/main/training.py#L507-L523), [L590-L604](https://github.com/ybdai7/Chameleon-durable-backdoor/blob/main/training.py#L590-L604))? Why is it not sufficient to apply the clipping once after the training or at least only once per epoch? Does this have an effect on the durability of the backdoor and / or the ASR?
2. Why did you comment out https://github.com/ybdai7/Chameleon-durable-backdoor/blob/main/helper.py#L225 while keeping the rest of the diff_privacy related code from "How to backdoor federated learning?"?
3. By disabling `diff_privacy` and `diff_privacy_contrastive` in `params_car_stripe_bg.yaml`, the attack stops to work completely (left one is with disabled diff_privacy):

![image](https://github.com/ybdai7/Chameleon-durable-backdoor/assets/73082071/6ac94b3b-9756-48e8-b041-9c4f6a215d8a)

If I understand it correctly, this is due to the fact, that enabling diff_privacy in malicious clients causes the model gradients to be projected onto a ball around the current global weights, which make it deviate less from the global model, and, hence, be less affected by NCD. Can you reproduce and confirm this effect? Have you every experimented with this effect? What were your findings and is it part of the attack to perform PGD, i.e., to frequently project the updates onto a ball around the current global model?

Thanks a lot in advance - I am looking forward to your reply!

**Comment by ybdai7** [comment]
Hi,

Thanks for your questions.

1. For L590-L640, we assume that the server is equipped with a norm-clipping defense, and will clip every received model update to an agreed bound. While for the other two clipping, it is actually performed by the attacker, who is aware of the clipping bound, and would like to clip its update to the agreed bound first to avoid the influence brought by the NCD. We do not discuss the impact of where the clipping happens influence the attack performance. Maybe you could have a try.
2. You can uncomment this to add noise in differential privacy in the server. It is just in this version we do not add this part.
3. Yes. That is actually proposed in the paper "Can you really backdoor Federated Learning" (i believe this is the title), which propose to use PGD to train the malicious model to bypass the NCD.

**Comment by simonla82** [comment]
Thanks for the very quick reply!

Some follow up questions:

1. Isn't the NCD clipping performed in line [L748-L754](https://github.com/ybdai7/Chameleon-durable-backdoor/blob/main/training.py#L748-L754)? L590-L640 is still in the adversary's training section, isn't it?
2. Alright, thanks. So, basically, these "diff_privacy" parts are more about PGD and NCD and not really about differential privacy, right?
3. Alright, thanks a lot!

**Comment by ybdai7** [comment]
Hi,

1. You are right. Sorry for the mistake.
2. Yes.

**Comment by simonla82** [comment]
Thanks again! Regarding 1.: If this is the case, my question remains: Why is this adversary-side clipping performed at three different places?

**Comment by ybdai7** [comment]
As you may notice in the paper, the malicious training using chameleon is divided into two stages: the contrastive stage and the projection stage. So we need to make sure that for each stage, the model update norm is restricted to a agreed bound. Thus, the first two clipping takes care of these two different training stages. The third clipping just wants to make sure the whole model is correctly clipped. As the first two already correctly restrict the training, removing the third one will not make any difference.

**Comment by simonla82** [comment]
Okay, that makes sense. Thank you!
